module.exports = {
  all: { type: "boolean" },
  automock: { type: "boolean" },
  bail: { alias: "b", type: "boolean" },
  cache: { type: "boolean" },
  cacheDirectory: { type: "string" },
  changedFilesWithAncestor: { type: "boolean" },
  changedSince: { nargs: 1, type: "string" },
  ci: { type: "boolean" },
  clearCache: { type: "boolean" },
  clearMocks: { type: "boolean" },
  collectCoverage: { type: "boolean" },
  collectCoverageFrom: { type: "string" },
  collectCoverageOnlyFrom: { string: true, type: "array" },
  color: { type: "boolean" },
  colors: { type: "boolean" },
  config: { alias: "c", type: "string" },
  coverage: { type: "boolean" },
  coverageDirectory: { type: "string" },
  coveragePathIgnorePatterns: { string: true, type: "array" },
  coverageProvider: { choices: ["babel", "v8"], type: "any" },
  coverageReporters: { string: true, type: "array" },
  coverageThreshold: { type: "string" },
  debug: { type: "boolean" },
  detectLeaks: { type: "boolean" },
  detectOpenHandles: { type: "boolean" },
  env: { type: "string" },
  errorOnDeprecated: { type: "boolean" },
  expand: { alias: "e", type: "boolean" },
  filter: { type: "string" },
  findRelatedTests: { type: "boolean" },
  forceExit: { type: "boolean" },
  globalSetup: { type: "string" },
  globalTeardown: { type: "string" },
  globals: { type: "string" },
  haste: { type: "string" },
  ignoreProjects: { string: true, type: "array" },
  init: { type: "boolean" },
  injectGlobals: { type: "boolean" },
  json: { type: "boolean" },
  lastCommit: { type: "boolean" },
  listTests: { type: "boolean" },
  logHeapUsage: { type: "boolean" },
  maxConcurrency: { type: "number" },
  maxWorkers: { alias: "w", type: "string" },
  moduleDirectories: { string: true, type: "array" },
  moduleFileExtensions: { string: true, type: "array" },
  moduleNameMapper: { type: "string" },
  modulePathIgnorePatterns: { string: true, type: "array" },
  modulePaths: { string: true, type: "array" },
  noStackTrace: { type: "boolean" },
  notify: { type: "boolean" },
  notifyMode: { type: "string" },
  onlyChanged: { alias: "o", type: "boolean" },
  onlyFailures: { alias: "f", type: "boolean" },
  outputFile: { type: "string" },
  passWithNoTests: { type: "boolean" },
  preset: { type: "string" },
  prettierPath: { type: "string" },
  projects: { string: true, type: "array" },
  reporters: { string: true, type: "array" },
  resetMocks: { type: "boolean" },
  resetModules: { type: "boolean" },
  resolver: { type: "string" },
  restoreMocks: { type: "boolean" },
  rootDir: { type: "string" },
  roots: { string: true, type: "array" },
  runInBand: { alias: "i", type: "boolean" },
  runTestsByPath: { type: "boolean" },
  runner: { type: "string" },
  selectProjects: { string: true, type: "array" },
  setupFiles: { string: true, type: "array" },
  setupFilesAfterEnv: { string: true, type: "array" },
  shard: { type: "string" },
  showConfig: { type: "boolean" },
  silent: { type: "boolean" },
  skipFilter: { type: "boolean" },
  snapshotSerializers: { string: true, type: "array" },
  testEnvironment: { type: "string" },
  testEnvironmentOptions: { type: "string" },
  testFailureExitCode: { type: "string" },
  testLocationInResults: { type: "boolean" },
  testMatch: { string: true, type: "array" },
  testNamePattern: { alias: "t", type: "string" },
  testPathIgnorePatterns: { string: true, type: "array" },
  testPathPattern: { string: true, type: "array" },
  testRegex: { string: true, type: "array" },
  testResultsProcessor: { type: "string" },
  testRunner: { type: "string" },
  testSequencer: { type: "string" },
  testTimeout: { type: "number" },
  transform: { type: "string" },
  transformIgnorePatterns: { string: true, type: "array" },
  unmockedModulePathPatterns: { string: true, type: "array" },
  updateSnapshot: { alias: "u", type: "boolean" },
  useStderr: { type: "boolean" },
  verbose: { type: "boolean" },
  watch: { type: "boolean" },
  watchAll: { type: "boolean" },
  watchPathIgnorePatterns: { string: true, type: "array" },
  watchman: { type: "boolean" },
}
